/*
 * This file was automatically generated by EvoSuite
 * Fri May 24 15:36:21 GMT 2019
 */

package com.example.hellosustechbackend.filestorage;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.example.hellosustechbackend.filestorage.FileStorageImpl;
import java.io.InputStream;
import java.nio.file.InvalidPathException;
import java.nio.file.Path;
import java.util.stream.Stream;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;
import org.springframework.core.io.Resource;
import org.springframework.web.multipart.MultipartFile;


public class FileStorageImpl_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FileStorageImpl fileStorageImpl0 = new FileStorageImpl();
      // Undeclared exception!
      try { 
        fileStorageImpl0.store((MultipartFile) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.example.hellosustechbackend.filestorage.FileStorageImpl", e);
      }
  }



  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      FileStorageImpl fileStorageImpl0 = new FileStorageImpl();
      MultipartFile multipartFile0 = mock(MultipartFile.class, new ViolatedAssumptionAnswer());
      doReturn((InputStream) null).when(multipartFile0).getInputStream();
      doReturn((String) null).when(multipartFile0).getOriginalFilename();
      fileStorageImpl0.store(multipartFile0);
  }


}
