/*
 * This file was automatically generated by EvoSuite
 * Fri May 24 15:10:42 GMT 2019
 */

package com.example.hellosustechbackend.service;

import org.junit.Test;
import static org.junit.Assert.*;
import com.example.hellosustechbackend.service.HelloService;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

public class HelloService_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      HelloService helloService0 = new HelloService();
      String string0 = helloService0.hello();
      assertEquals("Hello world", string0);
  }
}
