/*
 * This file was automatically generated by EvoSuite
 * Fri May 24 15:09:54 GMT 2019
 */

package com.example.hellosustechbackend.service;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.example.hellosustechbackend.service.UploadService;
import java.io.IOException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

public class UploadService_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      UploadService uploadService0 = new UploadService();
      // Undeclared exception!
      try { 
        uploadService0.readConsole((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      UploadService uploadService0 = new UploadService();
      // Undeclared exception!
      try { 
        uploadService0.readConsole("");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      UploadService uploadService0 = new UploadService();
      try { 
        uploadService0.readConsole("QPbS");
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Cannot start processes in a unit test
         //
      }
  }
}
