/*
 * This file was automatically generated by EvoSuite
 * Fri May 24 15:36:21 GMT 2019
 */

package com.example.hellosustechbackend.filestorage;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.example.hellosustechbackend.filestorage.FileStorageImpl;
import java.io.InputStream;
import java.nio.file.InvalidPathException;
import java.nio.file.Path;
import java.util.stream.Stream;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;
import org.springframework.core.io.Resource;
import org.springframework.web.multipart.MultipartFile;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FileStorageImpl_ESTest extends FileStorageImpl_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("./src/main/java/com/example/hellosustechbackend/filelocation.properties");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "Path");
      FileStorageImpl fileStorageImpl0 = new FileStorageImpl();
      Stream<Path> stream0 = fileStorageImpl0.loadFiles();
      assertNotNull(stream0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      FileStorageImpl fileStorageImpl0 = new FileStorageImpl();
      // Undeclared exception!
      try { 
        fileStorageImpl0.store((MultipartFile) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.example.hellosustechbackend.filestorage.FileStorageImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      FileStorageImpl fileStorageImpl0 = new FileStorageImpl();
      // Undeclared exception!
      try { 
        fileStorageImpl0.loadFile("");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.example.hellosustechbackend.filestorage.FileStorageImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("./src/main/java/com/example/hellosustechbackend/filelocation.properties");
      FileSystemHandling.appendStringToFile(evoSuiteFile0, "Path");
      byte[] byteArray0 = new byte[3];
      byteArray0[0] = (byte)58;
      FileSystemHandling.appendDataToFile(evoSuiteFile0, byteArray0);
      FileStorageImpl fileStorageImpl0 = null;
      try {
        fileStorageImpl0 = new FileStorageImpl();
        fail("Expecting exception: InvalidPathException");
      
      } catch(InvalidPathException e) {
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("./src/main/java/com/example/hellosustechbackend/filelocation.properties");
      FileSystemHandling.appendStringToFile(evoSuiteFile0, "");
      FileStorageImpl fileStorageImpl0 = null;
      try {
        fileStorageImpl0 = new FileStorageImpl();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("./src/main/java/com/example/hellosustechbackend/filelocation.properties");
      FileSystemHandling.appendStringToFile(evoSuiteFile0, "Path");
      FileStorageImpl fileStorageImpl0 = new FileStorageImpl();
      // Undeclared exception!
      try { 
        fileStorageImpl0.loadFile("Could not initialize storage!");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // FAIL!
         //
         verifyException("com.example.hellosustechbackend.filestorage.FileStorageImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("./src/main/java/com/example/hellosustechbackend/filelocation.properties");
      FileSystemHandling.appendStringToFile(evoSuiteFile0, "Path");
      FileStorageImpl fileStorageImpl0 = new FileStorageImpl();
      Resource resource0 = fileStorageImpl0.loadFile("");
      assertFalse(resource0.isOpen());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      FileStorageImpl fileStorageImpl0 = new FileStorageImpl();
      MultipartFile multipartFile0 = mock(MultipartFile.class, new ViolatedAssumptionAnswer());
      doReturn((InputStream) null).when(multipartFile0).getInputStream();
      doReturn((String) null).when(multipartFile0).getOriginalFilename();
      fileStorageImpl0.store(multipartFile0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      FileStorageImpl fileStorageImpl0 = new FileStorageImpl();
      // Undeclared exception!
      try { 
        fileStorageImpl0.deleteAll();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.example.hellosustechbackend.filestorage.FileStorageImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      FileStorageImpl fileStorageImpl0 = new FileStorageImpl();
      // Undeclared exception!
      try { 
        fileStorageImpl0.loadFiles();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.file.Files", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      FileStorageImpl fileStorageImpl0 = new FileStorageImpl();
      // Undeclared exception!
      try { 
        fileStorageImpl0.init();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.file.Files", e);
      }
  }
}
