/*
 * This file was automatically generated by EvoSuite
 * Fri May 24 15:32:15 GMT 2019
 */

package com.example.hellosustechbackend.model;

import org.junit.Test;
import static org.junit.Assert.*;
import com.example.hellosustechbackend.model.FileInfo;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;


public class FileInfo_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FileInfo fileInfo0 = new FileInfo("K1hD130-]Q;HO", "K1hD130-]Q;HO");
      fileInfo0.setUrl((String) null);
      String string0 = fileInfo0.getUrl();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      FileInfo fileInfo0 = new FileInfo("", (String) null);
      fileInfo0.setUrl(":,TzRF5?0Xo;1R");
      String string0 = fileInfo0.getUrl();
      assertEquals(":,TzRF5?0Xo;1R", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      FileInfo fileInfo0 = new FileInfo("", (String) null);
      fileInfo0.setFilename((String) null);
      String string0 = fileInfo0.getFilename();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      FileInfo fileInfo0 = new FileInfo("K1hD130-]Q;HO", "K1hD130-]Q;HO");
      String string0 = fileInfo0.getFilename();
      assertEquals("K1hD130-]Q;HO", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      FileInfo fileInfo0 = new FileInfo("", "");
      String string0 = fileInfo0.getFilename();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      FileInfo fileInfo0 = new FileInfo("", "");
      String string0 = fileInfo0.getUrl();
      assertEquals("", string0);
  }
}
