/*
 * This file was automatically generated by EvoSuite
 * Fri May 24 15:25:49 GMT 2019
 */

package com.example.hellosustechbackend.web;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import com.example.hellosustechbackend.service.ClassService;
import com.example.hellosustechbackend.web.ClassAPI;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.javaee.injection.Injector;
import org.junit.runner.RunWith;


public class ClassAPI_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ClassAPI classAPI0 = new ClassAPI();
      ClassService classService0 = mock(ClassService.class, new ViolatedAssumptionAnswer());
      doReturn((List) null).when(classService0).getClasses(anyInt() , anyInt());
      Injector.inject(classAPI0, (Class<?>) ClassAPI.class, "classService", (Object) classService0);
      Injector.validateBean(classAPI0, (Class<?>) ClassAPI.class);
      List<com.example.hellosustechbackend.domain.Class> list0 = classAPI0.viewClasses(3340, (-3262));
      assertNull(list0);
  }
}
