/*
 * This file was automatically generated by EvoSuite
 * Fri May 24 15:25:50 GMT 2019
 */

package com.example.hellosustechbackend.web;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.example.hellosustechbackend.filestorage.FileStorage;
import com.example.hellosustechbackend.web.DownloadFileAPI;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.javaee.injection.Injector;
import org.junit.runner.RunWith;
import org.springframework.core.io.Resource;
import org.springframework.http.ResponseEntity;


public class DownloadFileAPI_ESTest  {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DownloadFileAPI downloadFileAPI0 = new DownloadFileAPI();
      Resource resource0 = mock(Resource.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(resource0).toString();
      doReturn("j").when(resource0).getFilename();
      FileStorage fileStorage0 = mock(FileStorage.class, new ViolatedAssumptionAnswer());
      doReturn(resource0).when(fileStorage0).loadFile(anyString());
      Injector.inject(downloadFileAPI0, (Class<?>) DownloadFileAPI.class, "fileStorage", (Object) fileStorage0);
      Injector.validateBean(downloadFileAPI0, (Class<?>) DownloadFileAPI.class);
      ResponseEntity<Resource> responseEntity0 = downloadFileAPI0.downloadFile("j");
      assertTrue(responseEntity0.hasBody());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DownloadFileAPI downloadFileAPI0 = new DownloadFileAPI();
      FileStorage fileStorage0 = mock(FileStorage.class, new ViolatedAssumptionAnswer());
      doReturn((Resource) null).when(fileStorage0).loadFile(anyString());
      Injector.inject(downloadFileAPI0, (Class<?>) DownloadFileAPI.class, "fileStorage", (Object) fileStorage0);
      Injector.validateBean(downloadFileAPI0, (Class<?>) DownloadFileAPI.class);
      // Undeclared exception!
      try { 
        downloadFileAPI0.downloadFile("");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.example.hellosustechbackend.web.DownloadFileAPI", e);
      }
  }
}
