/*
 * This file was automatically generated by EvoSuite
 * Fri May 24 15:06:19 GMT 2019
 */

package com.example.hellosustechbackend.status;

import org.junit.Test;
import static org.junit.Assert.*;
import com.example.hellosustechbackend.status.Status;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

public class Status_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Status status0 = new Status();
      assertFalse(status0.isResult());
      
      status0.setResult(true);
      boolean boolean0 = status0.isResult();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Status status0 = new Status();
      status0.setDescription((String) null);
      status0.getDescription();
      assertFalse(status0.isResult());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Status status0 = new Status();
      status0.setDescription("B?w#D1~*Q@X^,|<`o");
      status0.getDescription();
      assertFalse(status0.isResult());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Status status0 = new Status(false, "SMEywH\"OX Tp>");
      assertFalse(status0.isResult());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Status status0 = new Status();
      boolean boolean0 = status0.isResult();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Status status0 = new Status();
      status0.getDescription();
      assertFalse(status0.isResult());
  }
}
